version: '2'

services:

  elasticsearch:
    image: mubee-elk.kr.ncr.ntruss.com/elasticsearch:0.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    network_mode: host

  logstash:
    image: mubee-elk.kr.ncr.ntruss.com/logstash:0.1 
    container_name: logstash
    volumes:
      - ./config/logstash/config:/usr/share/logstash/config
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
    network_mode: host

  kibana:
    image: mubee-elk.kr.ncr.ntruss.com/kibana:0.1
    container_name: kibana
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml 
    network_mode: host


